FROM rocker/geospatial

# Copy covidseq_dev and set permission
RUN mkdir -p /srv/shiny-server && rm -rf /srv/shiny-server/*
ADD ./covidapp /srv/shiny-server
RUN chmod -R +r /srv/shiny-server
RUN rm /srv/shiny-server/app.R
RUN mv /srv/shiny-server/app_customData.R /srv/shiny-server/app.R 

# Install deps and package
RUN R -e "devtools::install_deps('/srv/shiny-server')"
RUN R -e "devtools::install('/srv/shiny-server')"

# Expose port
EXPOSE 3838