FROM --platform=linux/amd64 microbialgenomics/shiny-geospatial:4.1.2

# Copy covidseq_dev and set permission
RUN rm -rf /srv/shiny-server/*
ADD ./covidapp /srv/shiny-server
RUN chmod -R +r /srv/shiny-server
RUN rm /srv/shiny-server/app.R
RUN mv /srv/shiny-server/app_customData.R /srv/shiny-server/app.R 

RUN apt-get update && apt-get install -y --no-install-recommends \
    libuv1 \
    libuv1-dev \
    cmake \
    make \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*
    
# Install deps and package
RUN R -e "devtools::install_deps('/srv/shiny-server')"
RUN R -e "devtools::install('/srv/shiny-server')"

# Expose port
EXPOSE 3838