name: ci

on:
  push:
    branches:
      - dev
      - main

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout covidseq dev breanch
        uses: actions/checkout@v2
        with:
          repository: MicrobialGenomics/covidseq
          ref: dev
          path: covidseq_dev

      - name: Checkout covidseq dev breanch
        uses: actions/checkout@v2
        with:
          repository: MicrobialGenomics/covidseq
          ref: main
          path: covidseq

      - name: Checkout covidapp main breanch
        uses: actions/checkout@v2
        with:
          repository: MicrobialGenomics/covidapp
          ref: main
          path: covidapp

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./covidseq_dev/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            microbialgenomics/shiny_apps:dev
